language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t fcaico/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fcaico/multi-docker npm test -- --coverage
  
after_success:
  - docker build -t fcaico/multi-client ./client
  - docker build -t fcaico/multi-nginx ./nginx
  - docker build -t fcaico/multi-server ./server
  - docker build -t fcaico/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push fcaico/multi-client
  - docker push fcaico/multi-nginx
  - docker push fcaico/multi-server
  - docker push fcaico/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-364871806390"
  bucket_path: "docker-multi"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
